---
aws_secrets_manager.settings:
  type: config_object
  label: 'AWS Secrets Manager Settings'
  mapping:
    aws_key:
      type: string
      label: 'AWS Key ID'
    aws_secret:
      type: string
      label: 'AWS Secret'
    aws_region:
      type: string
      label: 'AWS Region'
    secret_prefix:
      type: string
      label: 'Secret Prefix'
